		    			<arg line="${shellarg} asadmin --user admin --passwordfile ${file-gf-pwd} change-admin-password --domain_name domain1" />
          <arg line="${shellarg} asadmin --secure=false --interactive=false --passwordfile ${asadmin-password-file} --terse=false --user ${asadmin-user} --host ${appserver-host} --echo=true --port ${appserver-admin-port} delete-jvm-options \-XX\:NewRatio=2:-XX\:SurvivorRatio=10:-XX\:MaxPermSize=${glassfish-max-perm-size}:-XX\:-UseAdaptiveSizePolicy:-XX\:+UseParallelOldGC" />
          <arg line="${shellarg} asadmin --secure=false --interactive=false --passwordfile ${asadmin-password-file} --terse=false --user ${asadmin-user} --host ${appserver-host} --echo=true --port ${appserver-admin-port} create-jvm-options \-Xmn${glassfish-young-heap-size}:-XX\:+UseConcMarkSweepGC:-XX\:+UseParNewGC:-XX\:+ScavengeBeforeFullGC:-XX\:TargetSurvivorRatio=${glassfish-target-survivor-ratio}:-XX\:SurvivorRatio=${glassfish-survivor-ratio}:-XX\:+UseBiasedLocking:-XX\:MaxTenuringThreshold=${glassfish-max-tenuring-threshold}:-XX\:ParallelGCThreads=${glassfish-parallel-gc-threads}:-XX\:+OptimizeStringConcat:-XX\:+UseStringCache:-XX\:MaxPermSize=${glassfish-max-perm-size}:-XX\:+UseCompressedOops:-XX\:+UseCMSInitiatingOccupancyOnly:-XX\:CMSInitiatingOccupancyFraction=${glassfish-cms-initiating-occupancy-fraction}" />
          <arg line="${shellarg} asadmin --secure=false --interactive=false --passwordfile ${asadmin-password-file} --terse=false --user ${asadmin-user} --host ${appserver-host} --echo=true --port ${appserver-admin-port} create-jvm-options \-javaagent\:\${com.sun.aas.instanceRoot}/appagent/javaagent.jar" />
          <arg line='${shellarg} asadmin --host ${appserver-host} --port ${appserver-admin-port} --user ${asadmin-user} --passwordfile ${asadmin-password-file} set "server.thread-pools.thread-pool.http-thread-pool.max-thread-pool-size=${glassfish-request-processing-threadcount}"' />
          <arg line='${shellarg} asadmin --host ${appserver-host} --port ${appserver-admin-port} --user ${asadmin-user} --passwordfile ${asadmin-password-file} set "server.thread-pools.thread-pool.http-thread-pool.min-thread-pool-size=${glassfish-request-processing-initialthreadcount}"' />
          <arg line='${shellarg} asadmin --host ${appserver-host} --port ${appserver-admin-port} --user ${asadmin-user} --passwordfile ${asadmin-password-file} set "server.network-config.protocols.protocol.http-listener-1.http.request-timeout-seconds=${glassfish-request-processing-requesttimeout}"' />
          <arg line='${shellarg} asadmin --host ${appserver-host} --port ${appserver-admin-port} --user ${asadmin-user} --passwordfile ${asadmin-password-file} set "server.network-config.protocols.protocol.http-listener-1.http.header-buffer-length-bytes=${glassfish-request-processing-bufferlength}"' />
          <arg line='${shellarg} asadmin --host ${appserver-host} --port ${appserver-admin-port} --user ${asadmin-user} --passwordfile ${asadmin-password-file} set "server.network-config.protocols.protocol.http-listener-1.http.max-connections=${glassfish-keep-alive-maxconnections}"' />
          <arg line='${shellarg} asadmin --host ${appserver-host} --port ${appserver-admin-port} --user ${asadmin-user} --passwordfile ${asadmin-password-file} set "server.network-config.protocols.protocol.http-listener-1.http.timeout-seconds=${glassfish-keep-alive-timeout}"' />
          <arg line='${shellarg} asadmin --host ${appserver-host} --port ${appserver-admin-port} --user ${asadmin-user} --passwordfile ${asadmin-password-file} set "server.network-config.protocols.protocol.http-listener-1.http.send-buffer-size-bytes=32768"' />
          <arg line='${shellarg} asadmin --host ${appserver-host} --port ${appserver-admin-port} --user ${asadmin-user} --passwordfile ${asadmin-password-file} set "server.network-config.protocols.protocol.http-listener-2.http.request-timeout-seconds=${glassfish-request-processing-requesttimeout}"' />
          <arg line='${shellarg} asadmin --host ${appserver-host} --port ${appserver-admin-port} --user ${asadmin-user} --passwordfile ${asadmin-password-file} set "server.network-config.protocols.protocol.http-listener-2.http.header-buffer-length-bytes=${glassfish-request-processing-bufferlength}"' />
          <arg line='${shellarg} asadmin --host ${appserver-host} --port ${appserver-admin-port} --user ${asadmin-user} --passwordfile ${asadmin-password-file} set "server.network-config.protocols.protocol.http-listener-2.http.max-connections=${glassfish-keep-alive-maxconnections}"' />
          <arg line='${shellarg} asadmin --host ${appserver-host} --port ${appserver-admin-port} --user ${asadmin-user} --passwordfile ${asadmin-password-file} set "server.network-config.protocols.protocol.http-listener-2.http.timeout-seconds=${glassfish-keep-alive-timeout}"' />
          <arg line='${shellarg} asadmin --host ${appserver-host} --port ${appserver-admin-port} --user ${asadmin-user} --passwordfile ${asadmin-password-file} set "server.network-config.protocols.protocol.http-listener-2.http.send-buffer-size-bytes=32768"' />
